SC_ID = 1
NUM_ENGINES = 8
MAX_DEPTH = 99
SIM_LOG = 'Sim'

# Components
SPACECRAFT = 'sc'
HEATER = 'heater'
CATBED_HEATER = 'catbed_heater'

# Characteristics

VOLTAGE = 'voltage_impact_volts'
CURRENT = 'current_draw_amps'
MAIN_POWER_MEASUREMENTS = ([VOLTAGE, CURRENT])

# Properties
D_VOLTAGE = 'd_voltage'
D_AMPS = 'd_amps'

COMPONENT_PROPERTIES = {
    SPACECRAFT: {
        VOLTAGE: 35.0,
        CURRENT: 10.0
    },
    HEATER: {
        VOLTAGE: -0.001,
        CURRENT: 0.5
    }
}

INITIAL_SPACECRAFT_MAIN_POWER_VOLTS = \
    COMPONENT_PROPERTIES[SPACECRAFT][VOLTAGE]
INITIAL_SPACECRAFT_MAIN_POWER_CURRENT_AMPS = \
    COMPONENT_PROPERTIES[SPACECRAFT][CURRENT]

INITIAL_AMBIENT_TEMP_C = 20

ON_VOLTAGE_IMPACT_VOLTS = {HEATER: COMPONENT_PROPERTIES[HEATER][VOLTAGE]}
ON_CURRENT_DRAW_AMPS = {HEATER: COMPONENT_PROPERTIES[HEATER][CURRENT]}

THERMAL_CONTRIBUTION_DEG_C = {
    HEATER: 5,
    CATBED_HEATER: 150
}
